language: shell
os: linux
dist: xenial
addons:
  apt:
    packages: &default_packages
      - cmake
      - make
      - zlib1g-dev
      - libbz2-dev
      - vim-common
      - shellcheck

jobs:
  include:
    - addons:
        apt:
          packages:
            - *default_packages
            - build-essential
            - g++-8
            - gcc-8
      arch: arm64
      env: CC=gcc-8 CXX=g++-8 MMSEQS_NUM_THREADS=8
      dist: bionic
    - addons:
        apt:
          packages:
            - *default_packages
            - build-essential
            - g++-8
            - gcc-8
      arch: ppc64le
      dist: bionic
      env: CC=gcc-8 CXX=g++-8 MMSEQS_NUM_THREADS=4
    - addons:
        apt:
          packages:
            - *default_packages
            - clang-5.0
            - libc++-dev
            - libomp-dev
      env: CC=clang-5.0 CXX=clang++-5.0
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default_packages
            - gcc-4.9
            - g++-4.9
      env: CC=gcc-4.9 CXX=g++-4.9

before_install:
  - export CC
  - export CXX

script:
  - |
    if [[ -n "$MPI" ]]; then MPI=1; else MPI=0; fi; \
    mkdir build; cd build; \
    cmake -DHAVE_MPI="$MPI" ..;
    make -j ${MMSEQS_NUM_THREADS:-$(nproc --all)}; \
    cd ..; \
    ./util/run_regression.sh ./build/src/plass ./build/src/plass REGRESSION;
